version: '3'

services:

  nginx:
    network_mode: "host"

  duckdns:
    network_mode: "host"
    env_file:
      - './resources/secret.docker-env'

  # The reason for host mode is because of HA AutoDiscovery features
  ha:
    network_mode: "host"

  zwave:
    network_mode: "host"
